services:
  miner:
    image: kebab
    ports:
      - "6002:8080"
    build:
      target: migration
    environment:
      - POSTGRES_PASSWORD=S3cret
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=kebab_miner
    volumes:
      - pgdata:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d kebab_miner"]
      interval: 1s
      timeout: 5s
      retries: 10
volumes:
  pgdata: