CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Blocks" (
    "BlockId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Timestamp" timestamp with time zone NOT NULL,
    "BlockHash" bytea,
    "PreviousHash" bytea,
    "Nonce" text,
    CONSTRAINT "PK_Blocks" PRIMARY KEY ("BlockId")
);

CREATE TABLE "Transactions" (
    "Id" integer NOT NULL,
    "BlockId" integer NOT NULL,
    CONSTRAINT "PK_Transactions" PRIMARY KEY ("BlockId", "Id"),
    CONSTRAINT "FK_Transactions_Blocks_BlockId" FOREIGN KEY ("BlockId") REFERENCES "Blocks" ("BlockId") ON DELETE CASCADE
);

CREATE TABLE "TransactionInputs" (
    "BlockId" integer NOT NULL,
    "TransactionId" integer NOT NULL,
    "OutputIndex" integer NOT NULL,
    "TransactionBlockId" integer,
    "Signature" bytea NOT NULL,
    CONSTRAINT "PK_TransactionInputs" PRIMARY KEY ("BlockId", "TransactionId", "OutputIndex"),
    CONSTRAINT "FK_TransactionInputs_Transactions_TransactionBlockId_Transacti~" FOREIGN KEY ("TransactionBlockId", "TransactionId") REFERENCES "Transactions" ("BlockId", "Id")
);

CREATE TABLE "TransactionOutputs" (
    "BlockId" integer NOT NULL,
    "TransactionId" integer NOT NULL,
    "OutputIndex" integer NOT NULL,
    "TransactionBlockId" integer,
    "Value" integer NOT NULL,
    "PublicKey" text NOT NULL,
    "Nonce" integer NOT NULL,
    CONSTRAINT "PK_TransactionOutputs" PRIMARY KEY ("BlockId", "TransactionId", "OutputIndex"),
    CONSTRAINT "FK_TransactionOutputs_Transactions_TransactionBlockId_Transact~" FOREIGN KEY ("TransactionBlockId", "TransactionId") REFERENCES "Transactions" ("BlockId", "Id")
);

CREATE INDEX "IX_TransactionInputs_TransactionBlockId_TransactionId" ON "TransactionInputs" ("TransactionBlockId", "TransactionId");

CREATE INDEX "IX_TransactionOutputs_TransactionBlockId_TransactionId" ON "TransactionOutputs" ("TransactionBlockId", "TransactionId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240714203651_InitialCreate', '8.0.6');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250419173625_RemoveCircularDependencies', '8.0.6');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250419182448_AddCircularDependencies', '8.0.6');

COMMIT;


