// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace kebab.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kebab.Models.Transaction", b =>
                {
                    b.Property<int>("BlockId")
                        .HasColumnType("integer");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.HasKey("BlockId", "Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Kebab.Models.TransactionInput", b =>
                {
                    b.Property<int>("BlockId")
                        .HasColumnType("integer");

                    b.Property<string>("txid")
                        .HasColumnType("text");

                    b.Property<int>("OutputIndex")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Signature")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int?>("TransactionBlockId")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.HasKey("BlockId", "txid", "OutputIndex");

                    b.HasIndex("TransactionBlockId", "TransactionId");

                    b.ToTable("TransactionInputs");
                });

            modelBuilder.Entity("Kebab.Models.TransactionOutput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Nonce")
                        .HasColumnType("integer");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TransactionBlockId")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TransactionBlockId", "TransactionId");

                    b.ToTable("TransactionOutputs");
                });

            modelBuilder.Entity("Kebab.Models.TransactionInput", b =>
                {
                    b.HasOne("Kebab.Models.Transaction", null)
                        .WithMany("Inputs")
                        .HasForeignKey("TransactionBlockId", "TransactionId");
                });

            modelBuilder.Entity("Kebab.Models.TransactionOutput", b =>
                {
                    b.HasOne("Kebab.Models.Transaction", null)
                        .WithMany("Outputs")
                        .HasForeignKey("TransactionBlockId", "TransactionId");
                });

            modelBuilder.Entity("Kebab.Models.Transaction", b =>
                {
                    b.Navigation("Inputs");

                    b.Navigation("Outputs");
                });
#pragma warning restore 612, 618
        }
    }
}
